name: Deploy to S3

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
            uses: actions/checkout@v3

        - name: Install AWS CLI
            run: |
            sudo apt-get install -y python3-pip
            pip install awscli

        - name: Sync to S3
            env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
            run: |
                aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete --acl public-read