"""Change model Account: remove last_login_at, add email_verified, make firebase_uid not nullable

Revision ID: 1218a2bd3be4
Revises: 31a29c63deec
Create Date: 2025-04-22 14:18:34.796068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1218a2bd3be4'
down_revision = '31a29c63deec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))
        batch_op.drop_column('last_login_at')
        batch_op.alter_column('firebase_uid', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('email_verified')
        batch_op.alter_column('firebase_uid', nullable=True)

    # ### end Alembic commands ###
