"""Updated Account and User models: remove password, username, address; add Firebase fields

Revision ID: 31a29c63deec
Revises: 
Create Date: 2025-04-20 17:52:32.828491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a29c63deec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String()))
        batch_op.add_column(sa.Column('is_active', sa.Boolean()))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('accounts_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['firebase_uid'])
        batch_op.drop_column('username')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('street_address')
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('accounts_username_key', ['username'])
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
